### ISSUE TITLE
IndexError: list index out of range raised by mc.pl.divide_and_conquer_pipeline

### ISSUE THREAD

**Issue by tomsing1** [tanaylab/metacells#14]
After successfully reproducing the results from the [vignette](https://metacells.readthedocs.io/en/latest/Metacells_Vignette.html), I am now trying to process my own dataset.

Unfortunately, I get an error at the `divide_and_conquer_pipeline` step:

```python
mc.pl.divide_and_conquer_pipeline(clean,
                                  forbidden_gene_names=forbidden_gene_names,
                                  random_seed=123456)
```

The following error stack is raised (inside my jupyterlab notebook). I inspected the use of the compute cores. Initially, all cores are used, as expected. Just before this error is raised, only a single core is used (and that might be expected)?

Because I don't know which genes should be on the `forbidden_gene_names` list, yet, I initially ran this step passing an empty list as the `forbidden_gene_names` argument. I also tried a list containing a random subset of gene names. In both cases I ran into the error shown below. Anything obvious I might be doing wrong? 

```
set Microglia.clean.var[rare_gene_module_0]: 11 true (0.03577%) out of 30755 bools
set Microglia.clean.var[rare_gene_module_1]: 48 true (0.1561%) out of 30755 bools
set Microglia.clean.var[rare_gene]: 58 true (0.1886%) out of 30755 bools
set Microglia.clean.obs[cells_rare_gene_module]: 42430 outliers (99.71%) out of 42554 int32 elements with 2 groups with mean size 62
set Microglia.clean.obs[rare_cell]: 124 true (0.2914%) out of 42554 bools
/home/ubuntu/miniconda3/envs/metacells/lib/python3.8/site-packages/metacells/utilities/computation.py:347: UserWarning: sum of rows of a matrix with column_major layout
  warn(operating_on_matrix_of_wrong_layout)
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/metacells/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/ubuntu/miniconda3/envs/metacells/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/ubuntu/miniconda3/envs/metacells/lib/python3.8/site-packages/metacells/utilities/parallel.py", line 237, in _invocation
    return PARALLEL_FUNCTION(index)
  File "/home/ubuntu/miniconda3/envs/metacells/lib/python3.8/site-packages/metacells/pipeline/divide_and_conquer.py", line 1596, in compute_pile_metacells
    results = _compute_pile_metacells(pile_index)
  File "/home/ubuntu/miniconda3/envs/metacells/lib/python3.8/site-packages/metacells/pipeline/divide_and_conquer.py", line 1549, in _compute_pile_metacells
    compute_direct_metacells(pdata, what,
  File "/home/ubuntu/miniconda3/envs/metacells/lib/python3.8/site-packages/metacells/utilities/logging.py", line 347, in wrapper
    return function(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/metacells/lib/python3.8/site-packages/metacells/pipeline/direct.py", line 317, in compute_direct_metacells
    tl.compute_candidate_metacells(fdata,
  File "/home/ubuntu/miniconda3/envs/metacells/lib/python3.8/site-packages/metacells/utilities/logging.py", line 347, in wrapper
    return function(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/metacells/lib/python3.8/site-packages/metacells/tools/candidates.py", line 203, in compute_candidate_metacells
    _optimize_split_communities(  #
  File "/home/ubuntu/miniconda3/envs/metacells/lib/python3.8/site-packages/metacells/tools/candidates.py", line 312, in _optimize_split_communities
    _split_communities(outgoing_edge_weights=outgoing_edge_weights,
  File "/home/ubuntu/miniconda3/envs/metacells/lib/python3.8/site-packages/metacells/tools/candidates.py", line 382, in _split_communities
    _min_cut_community(outgoing_edge_weights=outgoing_edge_weights,
  File "/home/ubuntu/miniconda3/envs/metacells/lib/python3.8/site-packages/metacells/tools/candidates.py", line 446, in _min_cut_community
    cut, cut_strength = ut.min_cut(community_edge_weights)
  File "/home/ubuntu/miniconda3/envs/metacells/lib/python3.8/site-packages/metacells/utilities/computation.py", line 2296, in min_cut
    is_second[cut.partition[1]] = True
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

IndexError                                Traceback (most recent call last)
/tmp/ipykernel_33012/3512564858.py in <module>
----> 1 mc.pl.divide_and_conquer_pipeline(clean,
      2                                   forbidden_gene_names=clean.var.symbol.head().to_list(),
      3                                   #target_metacell_size=...,
      4                                   random_seed=123456)

~/miniconda3/envs/metacells/lib/python3.8/site-packages/metacells/utilities/logging.py in wrapper(*args, **kwargs)
    345                                          name, log_value)
    346 
--> 347                 return function(*args, **kwargs)
    348 
    349             finally:

~/miniconda3/envs/metacells/lib/python3.8/site-packages/metacells/pipeline/divide_and_conquer.py in divide_and_conquer_pipeline(adata, what, rare_max_gene_cell_fraction, rare_min_gene_maximum, rare_genes_similarity_method, rare_genes_cluster_method, rare_min_genes_of_modules, rare_min_cells_of_modules, rare_min_modules_size_factor, rare_min_module_correlation, rare_min_related_gene_fold_factor, rare_max_related_gene_increase_factor, rare_min_cell_module_total, rare_max_cells_of_random_pile, rare_dissolve_min_robust_size_factor, rare_dissolve_min_convincing_size_factor, rare_dissolve_min_convincing_gene_fold_factor, feature_downsample_min_samples, feature_downsample_min_cell_quantile, feature_downsample_max_cell_quantile, feature_min_gene_total, feature_min_gene_top3, feature_min_gene_relative_variance, feature_gene_names, feature_gene_patterns, forbidden_gene_names, forbidden_gene_patterns, cells_similarity_value_normalization, cells_similarity_log_data, cells_similarity_method, groups_similarity_log_data, groups_similarity_method, target_pile_size, max_cell_size, max_cell_size_factor, cell_sizes, pile_min_split_size_factor, pile_min_robust_size_factor, pile_max_merge_size_factor, target_metacell_size, knn_k, min_knn_k, knn_balanced_ranks_factor, knn_incoming_degree_factor, knn_outgoing_degree_factor, min_seed_size_quantile, max_seed_size_quantile, candidates_cooldown_pass, candidates_cooldown_node, candidates_cooldown_phase, candidates_min_split_size_factor, candidates_max_merge_size_factor, candidates_min_metacell_cells, candidates_max_split_min_cut_strength, candidates_min_cut_seed_cells, must_complete_cover, final_max_outliers_levels, deviants_min_gene_fold_factor, deviants_max_gene_fraction, deviants_max_cell_fraction, dissolve_min_robust_size_factor, dissolve_min_convincing_size_factor, dissolve_min_convincing_gene_fold_factor, dissolve_min_metacell_cells, random_seed)
    797 
    798         is_divide_and_conquer = \
--> 799             compute_divide_and_conquer_metacells(cdata, what,
    800                                                  feature_downsample_min_samples=feature_downsample_min_samples,
    801                                                  feature_downsample_min_cell_quantile=feature_downsample_min_cell_quantile,

~/miniconda3/envs/metacells/lib/python3.8/site-packages/metacells/utilities/logging.py in wrapper(*args, **kwargs)
    345                                          name, log_value)
    346 
--> 347                 return function(*args, **kwargs)
    348 
    349             finally:

~/miniconda3/envs/metacells/lib/python3.8/site-packages/metacells/pipeline/divide_and_conquer.py in compute_divide_and_conquer_metacells(adata, what, feature_downsample_min_samples, feature_downsample_min_cell_quantile, feature_downsample_max_cell_quantile, feature_min_gene_total, feature_min_gene_top3, feature_min_gene_relative_variance, feature_gene_names, feature_gene_patterns, forbidden_gene_names, forbidden_gene_patterns, cells_similarity_value_normalization, cells_similarity_log_data, cells_similarity_method, groups_similarity_log_data, groups_similarity_method, target_pile_size, max_cell_size, max_cell_size_factor, cell_sizes, pile_min_split_size_factor, pile_min_robust_size_factor, pile_max_merge_size_factor, target_metacell_size, knn_k, min_knn_k, knn_balanced_ranks_factor, knn_incoming_degree_factor, knn_outgoing_degree_factor, min_seed_size_quantile, max_seed_size_quantile, candidates_cooldown_pass, candidates_cooldown_node, candidates_cooldown_phase, candidates_min_split_size_factor, candidates_max_merge_size_factor, candidates_min_metacell_cells, candidates_max_split_min_cut_strength, candidates_min_cut_seed_cells, must_complete_cover, final_max_outliers_levels, deviants_min_gene_fold_factor, deviants_max_gene_fraction, deviants_max_cell_fraction, dissolve_min_robust_size_factor, dissolve_min_convincing_size_factor, dissolve_min_convincing_gene_fold_factor, dissolve_min_metacell_cells, random_seed)
   1104     try:
   1105         with ut.timed_step('.preliminary_metacells'):
-> 1106             compute_piled_metacells(adata, what,
   1107                                     phase='preliminary',
   1108                                     pile_of_cells=random_pile_of_cells,

~/miniconda3/envs/metacells/lib/python3.8/site-packages/metacells/utilities/logging.py in wrapper(*args, **kwargs)
    345                                          name, log_value)
    346 
--> 347                 return function(*args, **kwargs)
    348 
    349             finally:

~/miniconda3/envs/metacells/lib/python3.8/site-packages/metacells/pipeline/divide_and_conquer.py in compute_piled_metacells(adata, what, phase, pile_of_cells, feature_downsample_min_samples, feature_downsample_min_cell_quantile, feature_downsample_max_cell_quantile, feature_min_gene_total, feature_min_gene_top3, feature_min_gene_relative_variance, feature_gene_names, feature_gene_patterns, forbidden_gene_names, forbidden_gene_patterns, cells_similarity_value_normalization, cells_similarity_log_data, cells_similarity_method, groups_similarity_log_data, groups_similarity_method, target_pile_size, pile_min_split_size_factor, pile_min_robust_size_factor, pile_max_merge_size_factor, target_metacell_size, max_cell_size, max_cell_size_factor, cell_sizes, knn_k, min_knn_k, knn_balanced_ranks_factor, knn_incoming_degree_factor, knn_outgoing_degree_factor, min_seed_size_quantile, max_seed_size_quantile, candidates_cooldown_pass, candidates_cooldown_node, candidates_cooldown_phase, candidates_min_split_size_factor, candidates_max_merge_size_factor, candidates_min_metacell_cells, candidates_max_split_min_cut_strength, candidates_min_cut_seed_cells, must_complete_cover, final_max_outliers_levels, deviants_min_gene_fold_factor, deviants_max_gene_fraction, deviants_max_cell_fraction, dissolve_min_robust_size_factor, dissolve_min_convincing_size_factor, dissolve_min_convincing_gene_fold_factor, dissolve_min_metacell_cells, random_seed)
   1346 
   1347     subset_results = \
-> 1348         _run_parallel_piles(adata, what,
   1349                             phase=phase,
   1350                             piles_count=piles_count,

~/miniconda3/envs/metacells/lib/python3.8/site-packages/metacells/pipeline/divide_and_conquer.py in _run_parallel_piles(adata, what, phase, piles_count, pile_of_cells, feature_downsample_min_samples, feature_downsample_min_cell_quantile, feature_downsample_max_cell_quantile, feature_min_gene_total, feature_min_gene_top3, feature_min_gene_relative_variance, feature_gene_names, feature_gene_patterns, forbidden_gene_names, forbidden_gene_patterns, cells_similarity_value_normalization, cells_similarity_log_data, cells_similarity_method, target_metacell_size, max_cell_size, max_cell_size_factor, cell_sizes, knn_k, min_knn_k, knn_balanced_ranks_factor, knn_incoming_degree_factor, knn_outgoing_degree_factor, min_seed_size_quantile, max_seed_size_quantile, candidates_cooldown_pass, candidates_cooldown_node, candidates_cooldown_phase, candidates_min_split_size_factor, candidates_max_merge_size_factor, candidates_min_metacell_cells, candidates_max_split_min_cut_strength, candidates_min_cut_seed_cells, must_complete_cover, deviants_min_gene_fold_factor, deviants_max_gene_fraction, deviants_max_cell_fraction, dissolve_min_robust_size_factor, dissolve_min_convincing_size_factor, dissolve_min_convincing_gene_fold_factor, dissolve_min_metacell_cells, random_seed)
   1604         gc.collect()
   1605         ut.logger().debug('MAX_PARALLEL_PILES: %s', get_max_parallel_piles())
-> 1606         return list(ut.parallel_map(compute_pile_metacells, piles_count,
   1607                                     max_processors=get_max_parallel_piles()))
   1608 

~/miniconda3/envs/metacells/lib/python3.8/site-packages/metacells/utilities/parallel.py in parallel_map(function, invocations, max_processors)
    202             utm.timed_parameters(index=MAP_INDEX, processes=PROCESSES_COUNT)
    203             with get_context('fork').Pool(PROCESSES_COUNT) as pool:
--> 204                 return pool.map(_invocation, range(invocations))
    205     finally:
    206         IS_MAIN_PROCESS = True

~/miniconda3/envs/metacells/lib/python3.8/multiprocessing/pool.py in map(self, func, iterable, chunksize)
    362         in a list that is returned.
    363         '''
--> 364         return self._map_async(func, iterable, mapstar, chunksize).get()
    365 
    366     def starmap(self, func, iterable, chunksize=None):

~/miniconda3/envs/metacells/lib/python3.8/multiprocessing/pool.py in get(self, timeout)
    769             return self._value
    770         else:
--> 771             raise self._value
    772 
    773     def _set(self, i, obj):

IndexError: list index out of range
```

**Comment by tomsing1** [comment]
I managed to get through this step by filtering out some more cells with high number of total UMIs. Just a wild guess: perhaps some metacells end up containing only a single cell - with high enough total UMI count to preclude other cells to be grouped with them? And that list of length 1 is unexpected and leads to the `IndexError`. (I might be totally off the mark here, but spitballing...)

**Comment by orenbenkiki** [comment]
Note that final metacells have a minimal number of cells (12 by default), this is done to ensure a metacell actually reduces the technical sampling error by considering several samples of (hopefully the "same") transcriptome state.

That said, you might still be right - the error occurs in the line: `is_second[cut.partition[1]] = True` which happens when working on the metacell candidates, specifically trying to cut them into two to see whether they are "homogenous enough". Perhaps a candidate ended up being of size 1 which would explain the problem.

I'm adding a fix for this edge case in the next 0.6.1 release, which is coming "real soon" anyway, due to issues with the binary wheel creation. I'll be interested to see whether this will fix the problem. I'm keeping the issue open until then.

Thanks for reporting this!

**Comment by orenbenkiki** [comment]
Ok, I just pushed version 0.7.0 which should be resistent to this problem. Let me know if it actually fixed it so I can close this issue.

Thanks!

**Comment by tomsing1** [comment]
Great - version 0.7.0 successfully completes the `mc.pl.divide_and_conquer_pipeline` command even without filtering cells with high counts, e.g. it fixes the error I ran into. Many thanks!
