### ISSUE TITLE
AssertionError when calling find_noisy_lonely_genes()

### ISSUE THREAD

**Issue by lijinbio** [tanaylab/metacells#15]
Hi,

I tried to run mc.pl.analyze_clean_genes() but get the below assertion error invoked in find_noisy_lonely_genes().

```
set 10x3V31_13W_NRPE.var[properly_sampled_gene]: 28837 true (78.79%) out of 36601 bools
set 10x3V31_13W_NRPE.var[excluded_gene]: 13 true (0.03552%) out of 36601 bools
Traceback (most recent call last):
  File "<stdin>", line 8, in <module>
  File "<string>", line 15, in <module>
  File "/storage/chen/home/u236923/local/miniconda3/lib/python3.8/site-packages/metacells/utilities/logging.py", line 373, in wrapper
    return function(*args, **kwargs)
  File "/storage/chen/home/u236923/local/miniconda3/lib/python3.8/site-packages/metacells/pipeline/clean.py", line 101, in analyze_clean_genes
    tl.find_noisy_lonely_genes(
  File "/storage/chen/home/u236923/local/miniconda3/lib/python3.8/site-packages/metacells/utilities/logging.py", line 373, in wrapper
    return function(*args, **kwargs)
  File "/storage/chen/home/u236923/local/miniconda3/lib/python3.8/site-packages/metacells/tools/noisy_lonely.py", line 163, in find_noisy_lonely_genes
    assert ut.matrix_layout(htv_gene_ht_gene_similarity_matrix) == "row_major"
AssertionError
```

I am sure the matrix layout of the input matrix (x.X) is row_major, but not so sure why htv_gene_ht_gene_similarity_matrix is different in find_noisy_lonely_genes(). Could you please help suggest how could I resolve this assertion? Thanks.

**Comment by orenbenkiki** [comment]
The only thinks that comes to mind is that perhaps the matrix is 1x1 or something like that which throws the assertion off. That's pretty unlikely though...

Can you re-run this but add, immediately after `import metacells as mc`, the following lines:

```python
import logging
mc.ut.setup_logger(level=logging.DEBUG)
```

This should result in a very detailed log which would help verify or reject the above hypothesis. If this is the issue I'll be able to add a workaround - perhaps just remove this assertion.

As a temporary horrible hack you can manually edit `/storage/chen/home/u236923/local/miniconda3/lib/python3.8/site-packages/metacells/tools/noisy_lonely.py` and comment out this assertion...

**Comment by lijinbio** [comment]
By increasing the debug level, I got the below log.

```
#0 - PROCESSORS: 8
#0 - call analyze_clean_genes:
#0 -   with adata: 10x3V31_13W_NRPE annotated data with 5506 X 36601 float32s
#0 -   with what: __x__
#0 -   with properly_sampled_min_gene_total: 1
#0 -   with noisy_lonely_max_sampled_cells: 10000
#0 -   with noisy_lonely_downsample_min_samples: 750
#0 -   with noisy_lonely_downsample_min_cell_quantile: 0.05 (5%)
#0 -   with noisy_lonely_downsample_max_cell_quantile: 0.5 (50%)
#0 -   with noisy_lonely_min_gene_total: 100
#0 -   with noisy_lonely_min_gene_normalized_variance: 5.65685
#0 -   with noisy_lonely_max_gene_similarity: 0.1
#0 -   with excluded_gene_names: None
#0 -   with excluded_gene_patterns: [ MT-.* ]
#0 -   with random_seed: 12345 (reproducible)
#0 -   call find_properly_sampled_genes:
#0 -     with adata: 10x3V31_13W_NRPE annotated data with 5506 X 36601 float32s
#0 -     with what: __x__
#0 -     with min_gene_total: 1
#0 -     with inplace: True
#0 -     get 10x3V31_13W_NRPE.X: csc_matrix 5506 X 36601 float32s
#0 -     get 10x3V31_13W_NRPE.var[__x__|sum]: 36601 float32s with mean 610.1
#0 -     set 10x3V31_13W_NRPE.var[properly_sampled_gene]: 28837 true (78.79%) out of 36601 bools
#0 -   call find_named_genes:
#0 -     with adata: 10x3V31_13W_NRPE annotated data with 5506 X 36601 float32s
#0 -     with names: None
#0 -     with patterns: [ MT-.* ]
#0 -     with to: excluded_gene
#0 -     with invert: False
#0 -     set 10x3V31_13W_NRPE.var[excluded_gene]: 13 true (0.03552%) out of 36601 bools
#0 -   call find_noisy_lonely_genes:
#0 -     with adata: 10x3V31_13W_NRPE annotated data with 5506 X 36601 float32s
#0 -     with what: __x__
#0 -     with excluded_genes_mask: excluded_gene
#0 -     with max_sampled_cells: 10000
#0 -     with downsample_min_samples: 750
#0 -     with downsample_min_cell_quantile: 0.05 (5%)
#0 -     with downsample_max_cell_quantile: 0.5 (50%)
#0 -     with min_gene_total: 100
#0 -     with min_gene_normalized_variance: 5.65685
#0 -     with max_gene_similarity: 0.1
#0 -     with random_seed: 12345 (reproducible)
#0 -     with inplace: True
#0 -     call filter_data:
#0 -       with adata: unnamed annotated data with 5506 X 36601 float32s
#0 -       with obs_masks: [  ]
#0 -       with var_masks: [ ~excluded_gene ]
#0 -       with mask_obs: None
#0 -       with mask_var: None
#0 -       with invert_obs: False
#0 -       with invert_var: False
#0 -       with track_obs: None
#0 -       with track_var: sampled_gene_index
#0 -       with name: included
#0 -       with top_level: False
#0 -       call combine_masks:
#0 -         with adata: unnamed annotated data with 5506 X 36601 float32s
#0 -         with masks: [ ~excluded_gene ]
#0 -         with invert: False
#0 -         with to: None
#0 -         get unnamed.var[excluded_gene]: 13 true (0.03552%) out of 36601 bools
#0 -         calc ~excluded_gene: 36588 true (99.96%) out of 36601 bools
#0 -         return combined: 36588 true (99.96%) out of 36601 bools
#0 -       get unnamed.X: csc_matrix 5506 X 36601 float32s
#0 -       slice unnamed into included shape (5506, 36588)
#0 -       set included.var[sampled_gene_index]: 36588 int64s
#0 -     call downsample_cells:
#0 -       with adata: included annotated data with 5506 X 36588 float32s
#0 -       with what: __x__
#0 -       with downsample_min_cell_quantile: 0.05 (5%)
#0 -       with downsample_min_samples: 750
#0 -       with downsample_max_cell_quantile: 0.5 (50%)
#0 -       with random_seed: 12345 (reproducible)
#0 -       with inplace: True
#0 -       get included.X: csr_matrix 5506 X 36588 float32s
#0 -       get included.obs[__x__|sum]: 5506 float32s with mean 4043
#0 -       calc samples: 1943
#0 -       get included.X: csr_matrix 5506 X 36588 float32s
#0 -       set included.layers[downsampled]: csr_matrix 5506 X 36588 float32s
#0 -     call find_high_total_genes:
#0 -       with adata: included annotated data with 5506 X 36588 float32s
#0 -       with what: downsampled
#0 -       with min_gene_total: 100
#0 -       with inplace: True
#0 -       get included.layers[downsampled]: csc_matrix 5506 X 36588 float32s
#0 -       get included.var[downsampled|sum]: 36588 float32s with mean 288.3
#0 -       set included.var[high_total_gene]: 11304 true (30.9%) out of 36588 bools
#0 -     call filter_data:
#0 -       with adata: included annotated data with 5506 X 36588 float32s
#0 -       with obs_masks: [  ]
#0 -       with var_masks: [ high_total_gene ]
#0 -       with mask_obs: None
#0 -       with mask_var: None
#0 -       with invert_obs: False
#0 -       with invert_var: False
#0 -       with track_obs: None
#0 -       with track_var: None
#0 -       with name: high_total
#0 -       with top_level: False
#0 -       call combine_masks:
#0 -         with adata: included annotated data with 5506 X 36588 float32s
#0 -         with masks: [ high_total_gene ]
#0 -         with invert: False
#0 -         with to: None
#0 -         get included.var[high_total_gene]: 11304 true (30.9%) out of 36588 bools
#0 -         calc high_total_gene: 11304 true (30.9%) out of 36588 bools
#0 -         return combined: 11304 true (30.9%) out of 36588 bools
#0 -       get included.layers[downsampled]: csc_matrix 5506 X 36588 float32s
#0 -       slice included into high_total shape (5506, 11304)
#0 -     call compute_var_var_similarity:
#0 -       with adata: high_total annotated data with 5506 X 11304 float32s
#0 -       with what: downsampled
#0 -       with method: pearson
#0 -       with reproducible: True
#0 -       with logistics_location: 0.8
#0 -       with logistics_slope: 0.5
#0 -       with inplace: False
#0 -       get high_total.layers[downsampled]: SparseCSCView 5506 X 11304 float32s
#0 -     call find_high_normalized_variance_genes:
#0 -       with adata: high_total annotated data with 5506 X 11304 float32s
#0 -       with what: downsampled
#0 -       with min_gene_normalized_variance: 5.65685
#0 -       with inplace: False
#0 -       get high_total.layers[downsampled]: SparseCSCView 5506 X 11304 float32s
#0 -       return high_normalized_variance_genes: 1 true (0.008846%) out of 11304 bools
Traceback (most recent call last):
  File "<stdin>", line 9, in <module>
  File "<string>", line 19, in <module>
  File "/storage/chen/home/u236923/local/miniconda3/lib/python3.8/site-packages/metacells/utilities/logging.py", line 373, in wrapper
    return function(*args, **kwargs)
  File "/storage/chen/home/u236923/local/miniconda3/lib/python3.8/site-packages/metacells/pipeline/clean.py", line 101, in analyze_clean_genes
    tl.find_noisy_lonely_genes(
  File "/storage/chen/home/u236923/local/miniconda3/lib/python3.8/site-packages/metacells/utilities/logging.py", line 373, in wrapper
    return function(*args, **kwargs)
  File "/storage/chen/home/u236923/local/miniconda3/lib/python3.8/site-packages/metacells/tools/noisy_lonely.py", line 163, in find_noisy_lonely_genes
    assert ut.matrix_layout(htv_gene_ht_gene_similarity_matrix) == "row_major"
AssertionError
```

It seems that only one highly variable gene is calculated. Thanks.

**Comment by orenbenkiki** [comment]
`return high_normalized_variance_genes: 1 true (0.008846%) out of 11304 bools` confirms the hypothesis. Sigh. I'll release a patched version "soon". In the meanwhile, you can apply the manual patch disabling the assertion (horrible hack though this may be).

It is also very interesting this actually happens - it means the distribution of the gene values in your data is very strange... can you say something about this data?

**Comment by lijinbio** [comment]
Hi @orenbenkiki, yes, it works to manually disable the assertion. Thanks for the solution.

Our data is one sample of about 5000 single cells. The tissue is the retinal pigment epithelium (RPE), which is at the back of the human eyes. The cell clustering of RPE cells is typically compact of one cell type. I guess this compact cluster causes only HVGs calculated. As for "the distribution of the gene values in your data is very strange", I want to know sound metrics that I can calculate to systematically examine if the distribution of the gene values in my data is beyond normal. Could you please help suggest some metrics? or some approaches to look at the data? Thanks.

**Comment by orenbenkiki** [comment]
The part of the code does the following (it is described in the documentation): It computes for each gene its (var/mean). It then computes for each gene the median (var/mean) of the 101 genes with the closest expression level for this gene. Genes whose (var/mean) is higher than this median by some threshold (by default, 0.1) are good candidates for being feature genes.

In your case, for almost every gene, their (var/mean) was less than 0.1 above the median of the 100 genes with a similar expression level. This is "strange" (we've never seen anything like it in any of the data sets we've used MC1 and MC2 on).

I'd take a long hard look at the expression levels of the genes in the data (the raw UMIs count). Maybe there's something wrong there?

If the input data is real and not flawed somehow, could I get a copy of it so I could add it to my tests of the code? It would be a very interesting edge case to test code on.

BTW, you can look at which genes were chosen as features by looking at the `feature` per-gene/variable property which is filled by the pipeline. You would want to see a few hundred genes used... it sounds like in your case this would be way fewer genes, which "isn't good". I'd deeply distrust the results if the algorithm used less genes than that.

A way to increase the number of chosen feature genes is to reduce the value of the `feature_min_gene_relative_variance` parameter to the pipeline from the default 0.1 to something lower. Again, I'd be very surprised to see this is necessary on real data...

**Comment by youwh1996** [comment]
Similar error in our data
<img width="925" alt="WechatIMG669" src="https://user-images.githubusercontent.com/72308025/155839374-14e04db3-4bae-468f-b035-fedfbe00d8f2.png">

**Comment by youwh1996** [comment]
We also tried other datasets including the pbmc data in your vignette, but the same error was occurred

**Comment by orenbenkiki** [comment]
That is strange... First - lots of people have been running the PBMC vignette data, so if _that_ fails, there's something very wrong with the system (maybe some weird environment issue?). Second - the error above is different, it relates to the type of the elements of the data, which should be float32 for the system to work.
